### ISSUE TITLE
Is this still relevant ?

### ISSUE THREAD

**Issue by OmkarK45** [Raenton/prisma2-graphql-pagination#4]
Hey Raenton, thanks for creating this repo. I'm thinking of implementing Relay-style pagination using Prisma and Graphql. I wanted to ask if this method is still relevant as there are many changes in Prisma API. 

Again a huge thanks for creating this example.

**Comment by raenton** [comment]
Hi, I have not worked with Prisma or GraphQL since I made this project. It was just for testing things out. The GraphQL environment is definitely a lot maturer now, so it is possible that there are new conventions for it. Although I doubt the schema for the pagination would need to change. This is likely a good template for that. I believe I based this cursor pagination off of GraphQL's own example https://graphql.org/learn/pagination/

As for Prisma 2, I found the Database Abstraction Layer (Prisma Client) kind of limited. I also didn't like building schema-first. Although it's handy, I would prefer to write SQL directly to set up the database. I think Prisma has probably since grown a lot though. https://blog.logrocket.com/an-introduction-to-prisma-2/

It would be worth using this as a base and updating all the package versions to latest. Then you could see if if still works or not, and check the examples from GraphQL and Prisma's websites.

**Comment by OmkarK45** [comment]
No worries. Thanks!
